version: '3'
services:
  tao:
    container_name: tao1
    build: tao/
    image: talves/tao:0.11
    ports:
    - "80:80"
    links:
    - mysql
    restart: on-failure
    depends_on:
      - mysql
    environment:
    - HOSTNAME=localhost
  mysql:
    container_name: mysql1
    image: mysql:5
    ports:
    - "3306:3306"
    volumes:
      - mysqlvol:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=tao
    - MYSQL_USER=tao
    - MYSQL_PASSWORD=tao
volumes:
  mysqlvol:
